export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_LOADING = 'SET_LOADING'
export const FOCUS_REPO = 'FOCUS_REPO'
export const LOGOUT = 'LOGOUT'
export const ADD = 'ADD'
export const DEC = 'DEC'
